version: '3.8'
services:
  db:
    # ref https://stackoverflow.com/questions/76877963/setting-up-postgresql-database-server-in-docker-container-for-express-api
    image: postgres:latest
    restart: always
    environment:
      # defined in .env
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - node_network
    container_name: db

  app:
    # Runs the API
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      dev: 0
    networks:
      - node_network
    depends_on:
      - db
    ports:
      - '9006:9000'

networks:
  node_network: